# AUTOGENERATED! DO NOT EDIT! File to edit: ../Bearify_nb.ipynb.

# %% auto 0
__all__ = ['temp', 'learn', 'categories', 'image', 'labels', 'examples', 'intf', 'classify_image']

# %% ../Bearify_nb.ipynb 2
from fastai.vision.all import *
import gradio as gr

# %% ../Bearify_nb.ipynb 4
import pathlib
temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath

# %% ../Bearify_nb.ipynb 5
learn = load_learner('bear_model.pkl')

# %% ../Bearify_nb.ipynb 6
pathlib.PosixPath = temp

# %% ../Bearify_nb.ipynb 8
categories = ('Black', 'Grizzly', 'Teddy')

def classify_image(img):
  pred, idx, probs = learn.predict(img)
  return dict(zip(categories, map(float, probs)))

# %% ../Bearify_nb.ipynb 10
image = gr.Image()
labels = gr.Label()
examples = ['Images/teddy.jpg', 'Images/grizzly.jpg', 'Images/black.jpeg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=labels, examples=examples)
intf.launch(inline=False)
