<<<<<<< HEAD
import gradio as gr

def greet(name):
    return "Hello " + name + "!!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch()
=======
# AUTOGENERATED! DO NOT EDIT! File to edit: ../Bearify_nb.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'labels', 'examples', 'intf', 'classify_image']

# %% ../Bearify_nb.ipynb 2
from fastai.vision.all import *
import gradio as gr

# %% ../Bearify_nb.ipynb 5
learn = load_learner('bear_model.pkl')

# %% ../Bearify_nb.ipynb 7
categories = ('Black', 'Grizzly', 'Teddy')

def classify_image(img):
  pred, idx, probs = learn.predict(img)
  return dict(zip(categories, map(float, probs)))

# %% ../Bearify_nb.ipynb 9
image = gr.Image()
labels = gr.Label()
examples = ['Images/teddy.jpg', 'Images/grizzly.jpg', 'Images/black.jpeg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=labels, examples=examples)
intf.launch(inline=False)
>>>>>>> 0fe59f7a86f169cada64a4a2f46f4f824acce0cb
