# AUTOGENERATED! DO NOT EDIT! File to edit: ../Bearify_nb.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'labels', 'examples', 'intf', 'classify_image']

# %% ../Bearify_nb.ipynb 2
import os
import pathlib

import gradio as gr
from fastai.vision.all import *

# %% ../Bearify_nb.ipynb 4
# Check the operating system
if os.name == 'nt':  # 'nt' is the name for Windows NT (Windows)
    temp = pathlib.PosixPath
    pathlib.PosixPath = pathlib.WindowsPath

# Load the learner model
learn = load_learner('bear_model.pkl')

# Restore the original PosixPath if running on Windows
if os.name == 'nt':
    pathlib.PosixPath = temp

# %% ../Bearify_nb.ipynb 6
categories = ('Black', 'Grizzly', 'Teddy')

def classify_image(img):
  pred, idx, probs = learn.predict(img)
  return dict(zip(categories, map(float, probs)))

# %% ../Bearify_nb.ipynb 8
image = gr.Image()
labels = gr.Label()
examples = ['Images/teddy.jpg', 'Images/grizzly.jpg', 'Images/black.jpeg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=labels, examples=examples)
intf.launch(inline=False)
